export const CREATE_POSTS = 'CREATE_POSTS';
export const GET_POSTS = 'GET_POSTS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';

export const CREATE_POSTS_ERROR = 'CREATE_POSTS_ERROR';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const UPDATE_POSTS_ERROR = 'UPDATE_POSTS_ERROR';
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR';
