export const CREATE_POSTS = 'CREATE_POSTS';
export const GET_POSTS = 'GET_POSTS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const DELETE_POSTS = 'DELETE_POSTS';

export const CREATE_POSTS_ERROR = 'CREATE_POSTS_ERROR';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const UPDATE_POSTS_ERROR = 'UPDATE_POSTS_ERROR';
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR';

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
