export const GET_USER = 'GET_USER';
export const GET_USER_ERROR = 'GET_USER_ERROR';


export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR';
export const UNLIKE_POST = 'UNLIKE_POST';
export const UNLIKE_POST_ERROR = 'UNLIKE_POST_ERROR';

export const CREATE_COMMENTS = 'CREATE_COMMENTS';
export const CREATE_COMMENTS_ERROR = 'CREATE_COMMENTS_ERROR';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';